# Generated by Django 4.1.3 on 2023-03-23 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 23, 17, 58, 46, 714009, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
