# Generated by Django 4.1.3 on 2023-04-06 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_followers_user_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedBy', models.ManyToManyField(blank=True, null=True, related_name='User_who_is_being_followed', to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(blank=True, null=True, related_name='User_who_is_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
