# Generated by Django 4.1.3 on 2023-04-11 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_user_followers_remove_user_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_who_liked_the_post', to=settings.AUTH_USER_MODEL)),
                ('post_Liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_liked', to='network.posts')),
            ],
        ),
    ]
