# Generated by Django 4.1.3 on 2023-04-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
