# Generated by Django 4.1.3 on 2023-04-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follows',
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_who_is_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followedBy',
        ),
        migrations.AddField(
            model_name='follow',
            name='followedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_who_is_being_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
