# Generated by Django 4.1.3 on 2023-05-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_follow_follows_follow_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
